#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ==============================================================================
# author          :Ghislain Vieilledent
# email           :ghislain.vieilledent@cirad.fr, ghislainv@gmail.com
# web             :https://ecology.ghislainv.fr
# python_version  :>=2.7
# license         :GPLv3
# ==============================================================================

# Import
import os
import json

import ee

from geefcc import get_fcc

# "EARTHENGINE_TOKEN"
# https://github.com/gee-community/geemap/discussions/1341
# Find the Earth Engine credentials file on your computer.
# Open the credentials file and copy its content.
# On the GitHub Actions page, create a new secret
# with the name EARTHENGINE_TOKEN.

# Initialize GEE
ee_token = os.environ.get("EARTHENGINE_TOKEN")
credential_file_path = os.path.expanduser(
    "~/.config/earthengine/credentials")
if not os.path.exists(credential_file_path):
    os.makedirs(
        os.path.dirname(credential_file_path), exist_ok=True
    )
    if ee_token.startswith("{") and ee_token.endswith(
        "}"
    ):  # deals with token generated by new auth method (earthengine-api>=0.1.304).
        token_dict = json.loads(ee_token)
        with open(credential_file_path, "w") as f:
            f.write(json.dumps(token_dict))
    else:
        credential = (
            '{"refresh_token":"%s"}' % ee_token
        )  # deals with token generated by old auth method.
        with open(credential_file_path, "w") as f:
            f.write(credential)
ee.Initialize(project="forestatrisk",
              opt_url="https://earthengine-highvolume.googleapis.com")


def test_get_fcc():
    """Testing get_fcc()."""
    get_fcc(
        ee_project="forestatrisk",
        aoi="REU",
        buff=0.08983152841195216,
        years=[2000, 2010, 2020],
        source="tmf",
        perc=75,
        tile_size=0.5,
        output_file="tmp_outputs/fcc.tiff",
    )
    assert os.path.isfile("tmp_outputs/fcc.tiff")

# End
