"""Initialize GEE."""

import os
import json

import ee


def ee_initialize(token_name, project, **kwargs):
    r"""Initialize Google Earth Engine (GEE).

    Parameters
    ----------
    token_name : str
        The name of the environment variable containing the Earth Engine
        authentication token.
    project : str
        Name of the Google Cloud project to use with Earth Engine.
    **kwargs : dict, optional
        Additional keyword arguments passed to ``ee.Initialize()``. For
        example, ``opt_url='https://earthengine-highvolume.googleapis.com'``
        to use the Earth Engine High-Volume platform.

    Returns
    -------
    None
        This function initializes the Earth Engine session in place and
        does not return a value.

    Raises
    ------
    KeyError
        If the environment variable specified by ``token_name`` is not set
        or cannot be found.
    json.JSONDecodeError
        If the token value is a JSON-like string but cannot be parsed as
        valid JSON.
    ee.EEException
        If Earth Engine initialization fails due to invalid credentials or
        project configuration.

    Notes
    -----
    The function reads the authentication token from the environment variable
    specified by ``token_name``. If the Earth Engine credentials file does
    not already exist at ``~/.config/earthengine/credentials``, it will be
    created automatically.

    Two token formats are supported:

    - **New format** (``earthengine-api >= 0.1.304``): The token is a JSON
      string (starts and ends with ``{`` and ``}``). The parsed dictionary
      is written directly to the credentials file.
    - **Old format**: The token is a refresh token string, which is wrapped
      in ``{"refresh_token": "<token>"}`` before being written to the
      credentials file.

    Examples
    --------
    Initialize Earth Engine using the default endpoint:

    >>> import os
    >>> os.environ["MY_EE_TOKEN"] = '{"refresh_token": "my_token"}'
    >>> ee_initialize(token_name="MY_EE_TOKEN", project="my-gcp-project")

    Initialize Earth Engine using the High-Volume endpoint:

    >>> ee_initialize(
    ...     token_name="MY_EE_TOKEN",
    ...     project="my-gcp-project",
    ...     opt_url="https://earthengine-highvolume.googleapis.com",
    ... )
    """

    # Get credentials from environmental variable
    ee_token = os.environ.get(token_name)
    credential_file_path = os.path.expanduser(
        "~/.config/earthengine/credentials")

    # Write credentials
    if not os.path.exists(credential_file_path):
        os.makedirs(
            os.path.dirname(credential_file_path), exist_ok=True
        )
        if ee_token.startswith("{") and ee_token.endswith("}"):
            # deals with token generated by new auth method
            # (earthengine-api >= 0.1.304).
            token_dict = json.loads(ee_token)
            with open(credential_file_path, "w", encoding="utf-8") as f:
                f.write(json.dumps(token_dict))
        else:
            credential = (
                '{"refresh_token":"%s"}' % ee_token
            )  # deals with token generated by old auth method.
            with open(credential_file_path, "w", encoding="utf-8") as f:
                f.write(credential)

    # Initialize
    ee.Initialize(project=project, **kwargs)

# End
