"""Plot forest cover change map from TMF loss and gain product."""

from pathlib import Path
import math

import geopandas
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import rioxarray
from osgeo import gdal


def plot_fcc_loss_gain(
        input_file,
        output_file="fcc_loss_gain.png",
        title="Forest cover change, TMF",
        dpi=100,
        max_pixels=10_000_000,
        borders=None,
        grid=None,
        xlim=None,
        ylim=None):
    """Plot a forest cover change map from the TMF loss and gain product.

    Produces a PNG map from a raster file generated by
    :func:`get_fcc_loss_gain`. The seven transition classes (0--6) are
    each assigned a distinct color and a legend is added to the right of
    the map. Optionally, vector layers (borders, grid) can be overlaid
    and the spatial extent of the map can be controlled.

    If the raster exceeds ``max_pixels`` pixels, it is automatically
    resampled to a coarser resolution before plotting, using nearest
    neighbour resampling. The resampled raster is saved alongside the
    input file (suffix ``_coarsen.tif``) and reused on subsequent calls.

    Class definitions:

    - 0 = stable non-forest
    - 1 = stable forest
    - 2 = forest to deforested
    - 3 = non-forest to old regrowth
    - 4 = forest to old regrowth (via deforestation)
    - 5 = stable old regrowth
    - 6 = old regrowth to deforested

    Parameters
    ----------
    input_file : str or Path
        Path to the input GeoTIFF raster file produced by
        :func:`get_fcc_loss_gain`. Pixel values must be integers in the
        range 0--6.
    output_file : str or Path, optional
        Path to the output PNG file. Default is ``"fcc_loss_gain.png"``.
    title : str, optional
        Title displayed above the map. Default is
        ``"Forest cover change, TMF"``.
    dpi : int, optional
        Resolution of the output figure in dots per inch. Default is
        ``100``.
    max_pixels : int, optional
        Maximum number of pixels (rows x columns) allowed before
        automatic resampling is triggered. Default is ``10_000_000``.
    borders : str, Path, geopandas.GeoDataFrame, or None, optional
        Country or administrative borders to overlay as a black line.
        Default is ``None``.
    grid : str, Path, geopandas.GeoDataFrame, or None, optional
        Download tile grid to overlay as a grey line.
        Default is ``None``.
    xlim : tuple of float or None, optional
        Longitude limits as ``(xmin, xmax)``. Default is ``None``.
    ylim : tuple of float or None, optional
        Latitude limits as ``(ymin, ymax)``. Default is ``None``.

    Returns
    -------
    None
        The function writes the figure directly to ``output_file``.

    Examples
    --------
    Simple plot:

    >>> plot_fcc_loss_gain(
    ...     input_file="out_tmf_5yr/fcc_tmf.tif",
    ...     output_file="fcc_loss_gain.png",
    ...     title="Forest cover change 2015-2025, TMF",
    ...     dpi=100,
    ... )

    Plot with borders and grid:

    >>> plot_fcc_loss_gain(
    ...     input_file="out_tmf_5yr/fcc_tmf.tif",
    ...     output_file="fcc_tmf_5yr.png",
    ...     title="Forest cover change 2015-2025, TMF",
    ...     dpi=200,
    ...     borders="data/borders_NCL.gpkg",
    ...     grid="out_tmf_5yr/grid.gpkg",
    ...     xlim=(163, 169),
    ...     ylim=(-23.25, -18.75),
    ... )
    """

    input_file = Path(input_file)
    output_file = Path(output_file)

    # Load vector layers
    if isinstance(borders, (str, Path)):
        borders = geopandas.read_file(str(borders))
    if isinstance(grid, (str, Path)):
        grid = geopandas.read_file(str(grid))

    # Resample if raster exceeds max_pixels
    ds_info = gdal.Open(str(input_file))
    nrow = ds_info.RasterYSize
    ncol = ds_info.RasterXSize
    scale = ds_info.GetGeoTransform()[1]
    ds_info = None

    plot_file = input_file
    if nrow * ncol > max_pixels:
        factor = math.ceil(math.sqrt(nrow * ncol / max_pixels))
        xres = factor * scale
        yres = factor * scale
        coarsen_file = input_file.with_stem(input_file.stem + "_coarsen")
        if not coarsen_file.is_file():
            ds = gdal.Warp(
                str(coarsen_file), str(input_file),
                xRes=xres, yRes=yres, resampleAlg="near",
            )
            ds = None
        plot_file = coarsen_file

    # Colors
    cols = [
        (34, 139, 34, 255),
        (227, 26, 28, 255),
        (30, 100, 200, 255),
        (100, 160, 230, 255),
        (150, 190, 140, 255),
        (255, 140, 0, 255),
    ]
    cmax = 255.0
    colors = [(1, 1, 1, 0)]
    for col in cols:
        colors.append(tuple(c / cmax for c in col))
    color_map = ListedColormap(colors)

    # Labels
    labels = {
        0: "stable non-forest",
        1: "stable forest",
        2: "forest \u2192 deforested",
        3: "non-forest \u2192 old regrowth",
        4: "forest \u2192 old regrowth (via deforestation)",
        5: "stable old regrowth",
        6: "old regrowth \u2192 deforested",
    }
    patches = [
        mpatches.Patch(facecolor=col, edgecolor="black", label=labels[i])
        for i, col in enumerate(colors)
    ]

    # Load raster and compute geographic extent
    ds = rioxarray.open_rasterio(str(plot_file)).squeeze()
    nrow, ncol = ds.shape
    xmin = float(ds.x.min())
    xmax = float(ds.x.max())
    ymin = float(ds.y.min())
    ymax = float(ds.y.max())
    xres = (xmax - xmin) / (ncol - 1)
    yres = (ymax - ymin) / (nrow - 1)
    extent = [xmin - xres / 2, xmax + xres / 2,
              ymin - yres / 2, ymax + yres / 2]

    # Plot
    fig = plt.figure()
    ax = plt.subplot(111)
    ax.imshow(ds.values, cmap=color_map, extent=extent, resample=False)
    ax.set_aspect("equal")
    if grid is not None:
        grid.boundary.plot(ax=ax, color="grey", linewidth=0.5)
    if borders is not None:
        borders.boundary.plot(ax=ax, color="black", linewidth=0.5)
    if xlim is not None:
        ax.set_xlim(xlim)
    if ylim is not None:
        ax.set_ylim(ylim)
    plt.title(title)
    plt.legend(handles=patches, bbox_to_anchor=(1.05, 1),
               loc=2, borderaxespad=0.)
    fig.savefig(str(output_file), bbox_inches="tight", dpi=dpi)
    plt.close(fig)

# End
